name: Build PS-HDD-Tools

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Visual Studio
      uses: microsoft/setup-msbuild@v1.1
    - name: Download libusbK
      run: |
        try {
          Invoke-WebRequest -Uri "https://github.com/libusb/libusb/releases/download/v1.0.26/libusb-1.0.26-binaries.7z" -OutFile "libusb-1.0.26-binaries.7z" -ErrorAction Stop
          7z x libusb-1.0.26-binaries.7z -o"libusbK"
        } catch {
          Write-Error $_
          exit 1
        }
    - name: Create Build Directory
      run: mkdir build
    - name: Configure CMake
      run: cmake .. -G "Visual Studio 17 2022" -DLIBUSB_INCLUDE_DIR="./libusbK/include" -DLIBUSB_LIBRARY="./libusbK/lib/x64/libusbK.lib"
      working-directory: ./build
    - name: Build
      run: cmake --build . --config Release
      working-directory: ./build
    - name: Copy libusb dll
      run: Copy-Item -Path "./libusbK/lib/x64/libusb-1.0.dll" -Destination "./build/Release/"
    - name: Upload Artifact
      uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535
      with:
        name: windows-build
        path: ./build/Release/pshddtools.exe
    - name: Upload libusb dll
      uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535
      with:
        name: windows-libusb-dll
        path: ./build/Release/libusb-1.0.dll
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install cmake libusb-1.0-0-dev
    - name: Create Build Directory
      run: mkdir build
    - name: Configure CMake
      run: cmake ..
      working-directory: ./build
    - name: Build
      run: make
      working-directory: ./build
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: linux-build
        path: ./build/pshddtools
