name: Build PS-HDD-Tools

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Visual Studio
      uses: microsoft/setup-msbuild@v1.1
    - name: Create Build Directory
      run: mkdir build
    - name: Configure CMake
      run: cmake .. -G "Visual Studio 17 2022" -DLIBUSB_INCLUDE_DIR="C:/libusbK/include" -DLIBUSB_LIBRARY="C:/libusbK/lib/x64/libusbK.lib"
      working-directory: ./build
    - name: Build
      run: cmake --build . --config Release
      working-directory: ./build
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows-build
        path: ./build/Release/pshddtools.exe
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install cmake libusb-1.0-0-dev
    - name: Create Build Directory
      run: mkdir build
    - name: Configure CMake
      run: cmake ..
      working-directory: ./build
    - name: Build
      run: make
      working-directory: ./build
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: linux-build
        path: ./build/pshddtools
